#!/usr/bin/env bash
echo "Cloning dependencies"
git clone https://github.com/najahiiii/AnyKernel3.git -b asus --depth=1 AnyKernel
mkdir .signer && curl -sLo .signer/zipsigner-3.0.jar https://raw.githubusercontent.com/najahiiii/Noob-Script/noob/bin/zipsigner-3.0.jar
echo "Done"
if [ "$is_test" = true ]; then
     echo "Its alpha test build"
     unset chat_id
     unset token
     export chat_id=${my_id}
     export token=${nToken}
     export YEET=-Alpha
else
     echo "Its beta release build"
fi
GCC="/root/toolchain/ARM64/bin/aarch64-elf-"
GCC32="/root/toolchain/ARM/bin/arm-eabi-"
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
SHA=$(echo "$CIRCLE_SHA1" | cut -c 1-8)
TANGGAL=$(date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=Najahi
export KBUILD_BUILD_HOST=NusantaraDevs
# Push kernel to channel
function push() {
    cd .signer || exit 1
    ZIP=$(echo *.zip)
    curl -F document=@"$ZIP" "https://api.telegram.org/bot$token/sendDocument" \
        -F chat_id="$chat_id" \
        -F "disable_web_page_preview=true" \
        -F "parse_mode=html" \
        -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | For <b>ASUS ZENFONE MAX PRO M1 (X00T/D) Android 8.1 - 10.0</b> | <b>$(${GCC}gcc --version | head -n 1 | perl -pe 's/\(https.*?\)//gs' | sed  -e 's/  */ /g')</b>"
}
# Fin Error
function finerr() {
    curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
        -d chat_id="$chat_id" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=markdown" \
        -d text="Job Baking Chips throw an error(s)"
    exit 1
}
# Compile plox
function compile() {
    make -s -C "$(pwd)" -j"$(nproc)" O=out X00T_defconfig
    make -C "$(pwd)" O=out -j$(nproc) \
                   CROSS_COMPILE="${GCC}" \
                   CROSS_COMPILE_ARM32="${GCC32}"
    if ! [ -a "$IMAGE" ]; then
        finerr
        exit 1
    fi
    cp out/arch/arm64/boot/Image.gz-dtb AnyKernel
}
# Zipping
function zipping() {
    cd AnyKernel || exit 1
    zip -r9 unsigned.zip * -x LICENSE README.md
    mv unsigned.zip ../.signer/
    cd ..
}
# Signer
function signer() {
    cd .signer || exit 1
    if [ "$is_test" = true ]; then
        java -jar zipsigner-3.0.jar \
        unsigned.zip ChipsKernel-GCC-EAS-Alpha-"${TANGGAL}-${SHA}".zip
        rm unsigned.zip
    else
        java -jar zipsigner-3.0.jar \
        unsigned.zip ChipsKernel-GCC-EAS-"${TANGGAL}-${SHA}".zip
        rm unsigned.zip
    fi
    cd ..
}
compile
zipping
signer
END=$(date +"%s")
DIFF=$(($END - $START))
push
