#!/usr/bin/env bash
echo "Cloning dependencies"
git clone https://github.com/NusantaraDevs/clang.git --depth=1 -b dev/10.0 toolchain
git clone https://github.com/najahiiii/AnyKernel3.git -b asus --depth=1 AnyKernel
echo "Done"
if [ "$is_test" = true ]; then
     echo "Its alpha test build"
     unset chat_id
     unset token
     export chat_id=${my_id}
     export token=${nToken}
else
     echo "Its beta release build"
fi
SHA=$(echo "$CIRCLE_SHA1" | cut -c 1-8)
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
TANGGAL=$(date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=Najahi
export KBUILD_BUILD_HOST=NusantaraDevs
export LD_LIBRARY_PATH="$(pwd)/toolchain/bin/../lib:$PATH"
# Push kernel to channel
function push() {
    PATH="$(pwd)/toolchain/bin:${PATH}"
    cd AnyKernel || exit 1
    ZIP=$(echo ./*.zip)
    curl -F document=@"$ZIP" "https://api.telegram.org/bot$token/sendDocument" \
        -F chat_id="$chat_id" \
        -F "disable_web_page_preview=true" \
        -F "parse_mode=html" \
        -F caption="Build took $($DIFF / 60) minute(s) and $($DIFF % 60) second(s). | For <b>ASUS ZENFONE MAX PRO M1 (X00T/D) Android 8.1 - 9.0</b> | <b>$(clang --version | head -n 1 | perl -pe 's/\(https.*?\)//gs' | sed -e 's/  */ /g')</b>"
}
# Fin Error
function finerr() {
    curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
        -d chat_id="$chat_id" \
        -d "disable_web_page_preview=true" \
        -d "parse_mode=markdown" \
        -d text="Job Baking Chips throw an error(s)"
    exit 1
}
# Compile plox
function compile() {
    make -s -C "$(pwd)" -j"$(nproc)" O=out X00T_defconfig
    PATH="$(pwd)/toolchain/bin:${PATH}" \
    make -C "$(pwd)" -j"$(nproc)" O=out \
                   ARCH=arm64 \
                   CC=clang \
                   CLANG_TRIPLE=aarch64-linux-gnu- \
                   CROSS_COMPILE=aarch64-linux-gnu- \
                   CROSS_COMPILE_ARM32=arm-linux-gnueabi-
    if ! [ -a "$IMAGE" ]; then
        finerr
        exit 1
    fi
    cp out/arch/arm64/boot/Image.gz-dtb AnyKernel
}
# Zipping
function zipping() {
    cd AnyKernel || exit 1
    if [ "$is_test" = true ]; then
        zip -r9 ChipsKernel-Clang-EAS-Alpha-"${TANGGAL}-${SHA}".zip ./* -x LICENCE README.md
    else
        zip -r9 ChipsKernel-Clang-EAS-"${TANGGAL}-${SHA}".zip ./* -x LICENCE README.md
    fi #ngentod
    cd .. #well
}
compile
zipping
END=$(date +"%s")
DIFF=$($END - "$START")
push
