#!/bin/bash
CHECKPOINT="$(git log --pretty=format:'%h : %s' -1)"
case $CHECKPOINT in
	*"[rel]"*)
		echo -e "It is release build"
		export YEET=-r$CIRCLE_BUILD_NUM
	;;
	*)
		echo -e "teeeeeessssttt reeeeee"
		unset chat_id
		unset token
		export chat_id=${my_id}
		export token=${nToken}
		export YEET=-Alpha
	;;
esac
# sticker plox
function sticker() {
        curl -s -X POST "https://api.telegram.org/bot$token/sendSticker" \
                        -d sticker="CAADBQAD7wADQxCzIs_rqaRTwvagFgQ" \
                        -d chat_id=$chat_id
}
# Send info plox
function sendinfo() {
        curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
                        -d chat_id="$chat_id" \
                        -d "disable_web_page_preview=true" \
                        -d "parse_mode=html" \
                        -d text="<b>ChipsKernel</b> new build is up%0AStarted on <code>Circle CI</code>%0AFor device $(echo ${device})%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0AStarted on <code>$(TZ=Asia/Jakarta date)</code>%0A<b>CI Workflow information:</b> <a href='https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'>here</a>"
}
sticker
sendinfo
