#!bin/bash
git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b gcc5-20190314 gcc 
curl -F chat_id="$chat_id" -F sticker="CAADBQADxwADQxCzIgABXT-CE5tyWwI" https://api.telegram.org/bot$token/sendSticker
curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>ChipsKernel CAF</b> new build is up"'!'"%0AStarted on <code>$(hostname)</code>%0AFor device <b>ROLEX</b> (Redmi 4A)%0Abranch <code>"$(git rev-parse --abbrev-ref HEAD)"</code>%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiler <code>$(${PWD}/gcc/bin/aarch64-linux-gnu-gcc --version | head -n 1)</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested%0A<b>Semaphore CI Build Info</b> - <a href='https://semaphoreci.com/najahiiii/moaikernal'>Status</a>"
tanggal=$(date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=Najahi
export KBUILD_BUILD_HOST=SemaphoreCI
export USE_CCACHE=1 
export CACHE_DIR=~/.ccache
make -C $(pwd) O=out rolex_defconfig
make -C ${PWD} CROSS_COMPILE=${PWD}/gcc/bin/aarch64-linux-gnu- O=out -j6 -l4 > /dev/null || curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=markdown&text=Build throw an error(s)" > /dev/null
cp out/arch/arm64/boot/Image.gz-dtbAnyKernel/zImage
cd AnyKernel
zip -r9 ChipsKernel-Pie-GCC5-${tanggal}.zip *
END=$(date +"%s") 
DIFF=$(($END - $START))
curl -F chat_id="$chat_id" -F document=@"ChipsKernel-Pie-GCC5-${tanggal}.zip" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) seconds. | #unified" https://api.telegram.org/bot$token/sendDocument
cd ..
rm -rf out
rm -rf AnyKernel/zImage
rm -rf AnyKernel/ChipsKernel*.zip
