#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
echo "Cloning Toolchain, and AnyKernel"
git clone --quiet -j32 https://github.com/najahiiii/AnyKernel.git AnyKernel
git clone --quiet -j32 https://github.com/najahiiii/aarch64-linux-gnu.git -b 4.9-mirror gcc
echo "Done"
GCC="$(pwd)/gcc/bin/aarch64-linux-android-"
curl -s -F chat_id=$chat_id -F sticker="CAADBQAD7wADQxCzIs_rqaRTwvagAg" https://api.telegram.org/bot$token/sendSticker
curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>ChipsKernel Google-Common</b> new build is up"'!'"%0AStarted on <code>CircleCI</code>%0AFor device <b>ROLEX</b> (Redmi 4A)%0Abranch <code>$(git rev-parse --abbrev-ref HEAD)</code>%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiler <code>$(${GCC}gcc --version | head -n 1)</code>%0AStarted on <code>$(TZ=Asia/Jakarta date)</code>%0A<b>Build Status:</b> #untested"
tanggal=$(TZ=Asia/Jakarta date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=Najahi
export KBUILD_BUILD_HOST=CircleCI
# Push kernel to channel
function push() {
	ZIP=$(echo Chips*.zip)
	curl -F document=@$ZIP "https://api.telegram.org/bot$token/sendDocument" \
			-F chat_id="$chat_id" \
			-F "disable_web_page_preview=true" \
			-F "parse_mode=html" \
			-F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | <b>Build logs</b> <a href='${HASIL}'>here</a> | #unified"
}
# Function upload logs to my own server paste
function paste() {
    cat build.log | curl -F 'chips=<-' http://142.93.125.135 > link
    HASIL="$(cat link)"
}
# Fin Error
function finerr() {
        paste
        curl -s -X POST "https://api.telegram.org/bot$token/sendMessage" \
			-d chat_id="$chat_id" \
			-d "disable_web_page_preview=true" \
			-d "parse_mode=markdown" \
			-d text="Build throw an error(s) | **Build logs** [here](${HASIL})"
        exit 1
}
make -s -C $(pwd) O=out rolex_defconfig
make -C $(pwd) CROSS_COMPILE=${GCC} O=out -j32 -l32 2>&1| tee build.log
if ! [ -a $IMAGE ]; then
	finerr
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
paste
cd AnyKernel
zip -r9 ChipsKernel-Pie-GCommon-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
push
