#!bin/bash
IMAGE=$(pwd)/out/arch/arm64/boot/Image.gz-dtb
git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b gcc9-chips gcc
git clone https://github.com/najahiiii/DragonTC.git -b 9.0 dragontc
GCC="${(pwd)/gcc/bin/aarch64-chips-linux-gnu-"
CT="$(pwd)/dragontc/bin/clang"
curl -s -F chat_id=$chat_id -F sticker="CAADBQAD7wADQxCzIs_rqaRTwvagAg" https://api.telegram.org/bot$token/sendSticker
curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=html&text=<b>ChipsKernel CAF</b> new build is up"'!'"%0AStarted on <code>$(hostname)</code>%0AFor device <b>ROLEX</b> (Redmi 4A)%0Abranch <code>$(git rev-parse --abbrev-ref HEAD)</code>%0AUnder commit <code>$(git log --pretty=format:'"%h : %s"' -1)</code>%0ACompiler <code>$(${GCC}gcc --version | head -n 1)</code>%0AClang <code>$(${CT} --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')</code>%0AStarted on <code>$(date)</code>%0A<b>Build Status:</b> #untested%0A<b>Semaphore CI Build Info</b> - <a href='https://semaphoreci.com/najahiiii/moaikernal'>Status</a>"
tanggal=$(date +'%H%M-%d%m%y')
START=$(date +"%s")
export ARCH=arm64
export KBUILD_BUILD_USER=Najahi
export USE_CCACHE=1
export CACHE_DIR=~/.ccache
# Function to upload to pastebin.com
function pastebin() {
    title="build.log"
    expiration="N"
    token="ddfc4ce9d8ad271c0c02f4c6ba708b8e"
    input="$(cat build.log)"
    user_key="9a7a9136e6cc54ef0d82eb936d73be89"
    query="api_option=paste&api_dev_key=${token}&api_user_key=${user_key}&api_paste_code=${input}&api_paste_private=1&api_paste_name=${title}&api_paste_expire_date=${expiration}"
    curl -s -X POST https://pastebin.com/api/api_post.php -d "${query}" > link
    HASIL="$(cat link)"
}
# Function to upload to del.dog
function deldog() {
    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
        echo "ERROR: failed to post document" >&2
        exit 1
    }
    KEY=$(jq -r .key <<< "${RESULT}")
    echo "https://del.dog/raw/${KEY}"
}
# Fin Error
function finerr() {
        pastebin
        curl -s -X POST https://api.telegram.org/bot$token/sendMessage?chat_id=$chat_id -d "disable_web_page_preview=true" -d "parse_mode=html&text=Build throw an error(s) | <b>Build logs</b> <a href='${HASIL}'>here</a>"
        exit 1
}
make -s -C $(pwd) O=out rolex_defconfig
nohup make -s -C $(pwd) CC=${CT} CROSS_COMPILE=${GCC} O=out -j6 -l4 >> build.log
if ! [ -a $IMAGE ]; then
	finerr
	exit 1
fi
cp out/arch/arm64/boot/Image.gz-dtb AnyKernel/zImage
cd AnyKernel
zip -r9 ChipsKernel-Pie-DragonTC9-${tanggal}.zip *
END=$(date +"%s")
DIFF=$(($END - $START))
pastebin
curl -F chat_id="$chat_id" -F document=@"ChipsKernel-Pie-DragonTC9-${tanggal}.zip" -F "disable_web_page_preview=true" -F "parse_mode=html" -F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | <b>Build logs</b> <a href='${HASIL}'>here</a> | #unified" https://api.telegram.org/bot$token/sendDocument
cd ..
rm -rf out
rm -rf AnyKernel/zImage
rm -rf AnyKernel/ChipsKernel*.zip
