#!bin/bash/sh
git clone https://github.com/najahiiii/aarch64-linux-gnu.git -b linaro8-20190402 gcc
export ARCH=arm64
export KBUILD_BUILD_USER=Najahi
export USE_CCACHE=1
export CACHE_DIR=~/.ccache
export CROSS_COMPILE=$(pwd)/gcc/bin/aarch64-linux-gnu-
mkdir out
make -C $(pwd) O=out rolex_defconfig
make -C $(pwd) O=out -j$(nproc --all)
